FROM tiangolo/uwsgi-nginx-flask:python3.8

RUN apt-get update
RUN apt-get install -y libsndfile1-dev
RUN pip install tensorflow
RUN pip install librosa

COPY ./server.py /app
COPY ./keyword_spotting_service.py /app
COPY ./model.hdf5 /app
COPY ./app.ini /app

EXPOSE 3800

WORKDIR /app

ENTRYPOINT [ "uwsgi", "app.ini" ]

